### ISSUE TITLE
unable to upload a media content on deployed version

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#102]
For some reason there is an error when uploading a media content https://sparkednext.app/admin/media-content and it also seems there's a lot of calls made to the server when we do this, we should minimise those calls and also have thumbnail as optional, we should not require it.

**Comment by YewoMhango** [comment]
@OlivierJM  which are the multiple calls being made? Because for me it's only performing one call

**Comment by YewoMhango** [comment]
@OlivierJM  Is this still the case for you?
