### ISSUE TITLE
Library filters should be dynamic 

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#182]
Similar to here https://www.alemhulu.com/ Filters in the library should be dynamic, meaning that if you choose a grade then you should only see subjects under that specific grade on the filter, Then units & topics should be disabled until a Grade & Subject are selected. 
Also we should make a unit come show up before topic. 

![Screenshot 2024-06-05 at 07 45 03](https://github.com/SparkEdUAB/sparked-next/assets/11255454/4f333307-0658-47cc-8304-86403ea0c351)

**Comment by mikemtdev** [comment]
Shouldn't this filtering be done on the back end?

**Comment by brianmuks** [comment]
I will share the end points end of today

**Comment by brianmuks** [comment]
> * gradeId

For these end points my understanding is this:
`fetchSubjectsByGradeId` 
`fetchUnitsBySubjectId` 
@OlivierJM @mikemtdev please confirm

**Comment by brianmuks** [comment]
At the moment my understanding is that subjects and grades are not linked to topics ,media content and units. We need to implement this too right ?

**Comment by brianmuks** [comment]
> At the moment my understanding is that subjects and grades are not linked to topics ,media content and units. We need to implement this too right ?

@OlivierJM waiting for your response.

**Comment by brianmuks** [comment]
Thanks. This is helpful !

**Comment by mikemtdev** [comment]
@brianmuks you can ping me when you are ready

**Comment by brianmuks** [comment]
> @brianmuks you can ping me when you are ready

Sure

**Comment by mikemtdev** [comment]
Yes, I am adding what had remained.
