### ISSUE TITLE
Improve library view when no data has been added yet

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#184]
In case it is a fresh setup of the application, it should show a proper empty page instead of a blank screen on both side navigation and resource listing.

**Comment by YewoMhango** [comment]
You meant this view, right?

![Screenshot from 2024-06-12 12-01-43](https://github.com/SparkEdUAB/sparked-next/assets/78272760/5cebb28a-b6af-4a4c-9c69-7c8aceffd4db)

**Comment by YewoMhango** [comment]
What did you have in mind?

**Comment by YewoMhango** [comment]
Oh, okay, fine
