### ISSUE TITLE
Bugs on Dashboard

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#209]
Units don't show related subjects

<img width="2544" alt="Screenshot 2024-06-25 at 7 16 48 AM" src="https://github.com/SparkEdUAB/sparked-next/assets/11255454/66e985ee-a1ef-443b-9517-b22e2d5fbf4c">

Updating a subject with a grade fails

<img width="2258" alt="Screenshot 2024-06-25 at 7 17 11 AM" src="https://github.com/SparkEdUAB/sparked-next/assets/11255454/5818f108-fd45-4ff8-92ec-37459b55a597">

**Comment by YewoMhango** [comment]
> @YewoMhango kindly help look into this one if you can. 

Okay, let me check
