### ISSUE TITLE
Missing endpoints

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#225]
@brianmuks  I will keep a collection of endpoints that are currently missing or being used in a wrong place. 

- This is called `fetchTopicsBySubjectId_` but we are only returning a single topic https://github.com/SparkEdUAB/sparked-next/blob/0d7192c0e27ab715bc154dd6b62a9267f7904017/src/app/api/topic/index.ts#L260 since this is being/should be used on filters, we should return a list of topics that match the currently selected subject/units --> So it should return an array
- This is called `fetchUnitBySubjectId_` but it returns an array https://github.com/SparkEdUAB/sparked-next/blob/0d7192c0e27ab715bc154dd6b62a9267f7904017/src/app/api/unit/index.ts#L266 it should be named appropriately to avoid confusion 
- We should have ability to fetch media content by different fields https://github.com/SparkEdUAB/sparked-next/blob/main/src/app/api/media-content/index.ts
    - fetch by gradeId -- all basically everything 
    - fetch by unitId -- list of media that belong to the selected unit
    - fetch by topicId -- list of media that belong to the selected topic 

@brianmuks @mikemtdev @YewoMhango

**Comment by brianmuks** [comment]
Noted
