### ISSUE TITLE
Add support for multiple resource uploads

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#66]
We need a way to upload multiple resources, I am not sure yet how to do this but we can figure it out together

**Comment by YewoMhango** [comment]
By this, you mean making it easy for people to create and upload lots of media content when they have many files which need uploading, or uploading multiple files for the same "Media Content" item?

**Comment by YewoMhango** [comment]
Okay, I see

**Comment by YewoMhango** [comment]
@OlivierJM so my first thought was that we could first allow the uploader to select the topic and select multiple files, and then show all those items in a list (maybe using an Accordion list or similar). From there, the one uploading can edit the details for each resource individually (like the name, description), and then press submit to upload them all. What do you think?
