### ISSUE TITLE
Improve the resource view section 

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#71]
The left section here should maybe list all courses(grades) then on dropdown the units 

The top part that currently shows tags maybe should show all topics based on currently selected grade/units, then for the resources since these are likely to be many, we should make the cards a little bit smaller to accommodate more in a view. 

This is also one example where the #62 will work since we don't want to fetch all the resources, we can show 20 by default and then as they scroll we fetch more, we can use this or something better if there's https://github.com/ankeetmaini/react-infinite-scroll-component#readme 

<img width="1792" alt="Screenshot 2024-04-11 at 07 04 01" src="https://github.com/OlivierJM/sparked-next/assets/11255454/e324cd79-7b8a-40c0-8b7a-6c11d59be4ff">

**Comment by YewoMhango** [comment]
@OlivierJM In what way should it be responsive for tablet devices specifically? Because I also made it responsive for mobile devices, so I didn't consider much tablet devices specifically

**Comment by YewoMhango** [comment]
> @YewoMhango I saw the changes for this, it looks great 🚀

Okay, great 😊

**Comment by YewoMhango** [comment]
@OlivierJM Should the library media content search page also use infinite scrolling?

**Comment by YewoMhango** [comment]
Okay. I've actually already written it out, but for the main list only, not for the search page
