### ISSUE TITLE
URGENT - Convert endpoints to GET 

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/sparked-next#85]
For better performance and to be able to achieve this #60 we need to have fetch endpoints as GET instead of POST. 

For dashboard

- fetch courses
- fetch units
- fetch topics
- fetch media contents

For client

- fetch units
- fetch topics
- fetch media contents
- fetch individual media content. 

@brianmuks this is blocking #60 it would be great if we can start on this especially dashboard links.

**Comment by brianmuks** [comment]
@OlivierJM I have take note of this and I will start working on it asap.

**Comment by brianmuks** [comment]
I hit a broker on this one. Submitting a solution tonight.
